/* The following code was generated by JFlex 1.4.3 on 8/1/21 6:30 PM */

package codigo;
import static codigo.Tokens.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 8/1/21 6:30 PM from the specification file
 * <tt>E:/GitHub Projects/analisador_lexico/AnalizadorLexico/src/codigo/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\36\2\0\1\3\22\0\1\3\7\0\1\43\1\44"+
    "\1\42\1\40\1\3\1\41\1\0\1\35\12\2\3\0\1\37\3\0"+
    "\22\1\1\17\7\1\4\0\1\1\1\0\1\16\1\12\1\24\1\7"+
    "\1\14\1\15\1\21\1\23\1\4\1\1\1\27\1\13\1\33\1\5"+
    "\1\10\1\30\1\1\1\20\1\22\1\6\1\11\1\31\1\26\1\32"+
    "\1\25\1\34\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\20\2\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\1\1\2\1\13\5\2"+
    "\1\13\33\2\1\4\1\0\1\13\44\2\1\0\27\2"+
    "\1\3\4\2\1\13\3\2\1\13\36\2";

  private static int [] zzUnpackAction() {
    int [] result = new int[166];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\45\0\112\0\157\0\224\0\271\0\336\0\u0103"+
    "\0\u0128\0\u014d\0\u0172\0\u0197\0\u01bc\0\u01e1\0\u0206\0\u022b"+
    "\0\u0250\0\u0275\0\u029a\0\u02bf\0\u02e4\0\u0309\0\45\0\45"+
    "\0\45\0\45\0\45\0\u032e\0\u0353\0\112\0\u0378\0\u039d"+
    "\0\u03c2\0\u03e7\0\u040c\0\u0431\0\u0456\0\u047b\0\u04a0\0\u04c5"+
    "\0\u04ea\0\u050f\0\u0534\0\u0559\0\u057e\0\u05a3\0\u05c8\0\u05ed"+
    "\0\u0612\0\u0637\0\u065c\0\u0681\0\u06a6\0\u06cb\0\u06f0\0\u0715"+
    "\0\u073a\0\u075f\0\u0784\0\u07a9\0\u07ce\0\u07f3\0\u0818\0\u083d"+
    "\0\u0862\0\u0887\0\u08ac\0\u08d1\0\u08f6\0\u091b\0\u0940\0\u0965"+
    "\0\u098a\0\u09af\0\u09d4\0\u09f9\0\u0a1e\0\u0a43\0\u0a68\0\u0a8d"+
    "\0\u0ab2\0\u0ad7\0\u0afc\0\u0b21\0\u0b46\0\u0b6b\0\u0b90\0\u0bb5"+
    "\0\u0bda\0\u0bff\0\u0c24\0\u0c49\0\u0c6e\0\u0c93\0\u0cb8\0\u0cdd"+
    "\0\u0d02\0\u0d27\0\u0d4c\0\u0d71\0\u0d96\0\u0dbb\0\u0de0\0\u0e05"+
    "\0\u0e2a\0\u0e4f\0\u0e74\0\u0e99\0\u0ebe\0\u0ee3\0\u0f08\0\u0f2d"+
    "\0\u0f52\0\u0f77\0\u0f9c\0\u0fc1\0\u0fe6\0\u100b\0\u1030\0\u1055"+
    "\0\u107a\0\u109f\0\u10c4\0\u10e9\0\u110e\0\u1133\0\45\0\u1158"+
    "\0\u117d\0\u11a2\0\u11c7\0\u0940\0\u11ec\0\u1211\0\u1236\0\u125b"+
    "\0\u1280\0\u12a5\0\u12ca\0\u12ef\0\u1314\0\u1339\0\u135e\0\u1383"+
    "\0\u13a8\0\u13cd\0\u13f2\0\u1417\0\u143c\0\u1461\0\u1486\0\u14ab"+
    "\0\u14d0\0\u14f5\0\u151a\0\u153f\0\u1564\0\u1589\0\u15ae\0\u15d3"+
    "\0\u15f8\0\u161d\0\u1642\0\u1667\0\u168c\0\u16b1";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[166];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\2\3\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\3\1\21\1\3\1\22\1\3\1\23\1\3\1\24"+
    "\1\25\3\3\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\2\46\0\2\3\1\0\31\3\12\0\1\4"+
    "\45\0\1\5\42\0\2\3\1\0\1\3\1\35\7\3"+
    "\1\36\15\3\1\37\1\3\11\0\2\3\1\0\10\3"+
    "\1\40\1\3\1\41\16\3\11\0\2\3\1\0\14\3"+
    "\1\42\2\3\1\43\11\3\11\0\2\3\1\0\4\3"+
    "\1\44\3\3\1\45\20\3\11\0\2\3\1\0\4\3"+
    "\1\46\7\3\1\47\4\3\1\50\7\3\11\0\2\3"+
    "\1\0\4\3\1\51\24\3\11\0\2\3\1\0\7\3"+
    "\1\52\16\3\1\53\2\3\11\0\2\3\1\0\1\54"+
    "\6\3\1\55\21\3\11\0\2\3\1\0\6\3\1\56"+
    "\7\3\1\57\12\3\11\0\2\3\1\0\2\3\1\60"+
    "\26\3\11\0\2\3\1\0\10\3\1\61\20\3\11\0"+
    "\2\3\1\0\2\3\1\62\2\3\1\63\11\3\1\64"+
    "\1\3\1\65\1\66\6\3\11\0\2\3\1\0\4\3"+
    "\1\67\2\3\1\70\2\3\1\71\4\3\1\72\11\3"+
    "\11\0\2\3\1\0\17\3\1\73\11\3\11\0\2\3"+
    "\1\0\5\3\1\74\4\3\1\75\1\3\1\76\14\3"+
    "\11\0\2\3\1\0\4\3\1\77\24\3\45\0\1\100"+
    "\50\0\1\101\4\0\2\3\1\0\2\3\1\102\13\3"+
    "\1\103\12\3\11\0\2\3\1\0\24\3\1\104\4\3"+
    "\11\0\2\3\1\0\22\3\1\36\6\3\11\0\2\3"+
    "\1\0\2\3\1\105\26\3\11\0\2\3\1\0\12\3"+
    "\1\106\6\3\1\36\7\3\11\0\2\3\1\0\1\107"+
    "\13\3\1\110\14\3\11\0\2\3\1\0\5\3\1\111"+
    "\23\3\11\0\2\3\1\0\11\3\1\112\17\3\11\0"+
    "\2\3\1\0\4\3\1\113\24\3\11\0\2\3\1\0"+
    "\10\3\1\114\20\3\11\0\2\3\1\0\2\3\1\115"+
    "\26\3\11\0\2\3\1\0\1\3\1\116\27\3\11\0"+
    "\2\3\1\0\16\3\1\115\12\3\11\0\2\3\1\0"+
    "\2\3\1\117\26\3\11\0\2\3\1\0\1\3\1\120"+
    "\27\3\11\0\2\3\1\0\4\3\1\121\24\3\11\0"+
    "\2\3\1\0\16\3\1\122\12\3\11\0\2\3\1\0"+
    "\16\3\1\123\12\3\11\0\2\3\1\0\14\3\1\124"+
    "\14\3\11\0\2\3\1\0\2\3\1\125\26\3\11\0"+
    "\2\3\1\0\12\3\1\126\1\3\1\127\14\3\11\0"+
    "\2\3\1\0\24\3\1\130\4\3\11\0\2\3\1\0"+
    "\4\3\1\131\24\3\11\0\2\3\1\0\1\3\1\132"+
    "\27\3\11\0\2\3\1\0\1\133\30\3\11\0\2\3"+
    "\1\0\1\3\1\134\27\3\11\0\2\3\1\0\12\3"+
    "\1\135\16\3\11\0\2\3\1\0\2\3\1\136\13\3"+
    "\1\115\12\3\11\0\2\3\1\0\12\3\1\137\16\3"+
    "\11\0\2\3\1\0\1\140\30\3\11\0\2\3\1\0"+
    "\6\3\1\141\22\3\11\0\2\3\1\0\20\3\1\142"+
    "\10\3\11\0\2\3\1\0\1\143\3\3\1\144\24\3"+
    "\11\0\2\3\1\0\1\145\6\3\1\146\21\3\10\0"+
    "\36\100\1\0\6\100\2\0\1\147\43\0\2\3\1\0"+
    "\10\3\1\150\20\3\11\0\2\3\1\0\2\3\1\151"+
    "\26\3\11\0\2\3\1\0\4\3\1\131\2\3\1\152"+
    "\21\3\11\0\2\3\1\0\1\153\30\3\11\0\2\3"+
    "\1\0\1\3\1\154\27\3\11\0\2\3\1\0\16\3"+
    "\1\36\12\3\11\0\2\3\1\0\4\3\1\155\24\3"+
    "\11\0\2\3\1\0\6\3\1\140\22\3\11\0\2\3"+
    "\1\0\12\3\1\156\16\3\11\0\2\3\1\0\7\3"+
    "\1\157\21\3\11\0\2\3\1\0\12\3\1\160\16\3"+
    "\11\0\2\3\1\0\10\3\1\36\20\3\11\0\2\3"+
    "\1\0\15\3\1\36\13\3\11\0\2\3\1\0\10\3"+
    "\1\161\20\3\11\0\2\3\1\0\12\3\1\162\16\3"+
    "\11\0\2\3\1\0\12\3\1\163\16\3\11\0\2\3"+
    "\1\0\2\3\1\164\26\3\11\0\2\3\1\0\10\3"+
    "\1\131\20\3\11\0\2\3\1\0\1\51\30\3\11\0"+
    "\2\3\1\0\5\3\1\165\23\3\11\0\2\3\1\0"+
    "\2\3\1\166\26\3\11\0\2\3\1\0\1\167\30\3"+
    "\11\0\2\3\1\0\10\3\1\137\20\3\11\0\2\3"+
    "\1\0\14\3\1\163\14\3\11\0\2\3\1\0\20\3"+
    "\1\170\10\3\11\0\2\3\1\0\2\3\1\136\26\3"+
    "\11\0\2\3\1\0\2\3\1\171\26\3\11\0\2\3"+
    "\1\0\16\3\1\107\12\3\11\0\2\3\1\0\20\3"+
    "\1\172\10\3\11\0\2\3\1\0\14\3\1\36\14\3"+
    "\11\0\2\3\1\0\7\3\1\115\21\3\11\0\2\3"+
    "\1\0\7\3\1\166\21\3\11\0\2\3\1\0\23\3"+
    "\1\173\5\3\11\0\2\3\1\0\25\3\1\174\3\3"+
    "\11\0\2\3\1\0\2\3\1\175\26\3\11\0\2\3"+
    "\1\0\3\3\1\36\25\3\11\0\2\3\1\0\12\3"+
    "\1\176\16\3\12\0\1\147\41\0\1\177\1\0\2\3"+
    "\1\0\14\3\1\200\14\3\11\0\2\3\1\0\12\3"+
    "\1\201\16\3\11\0\2\3\1\0\10\3\1\202\20\3"+
    "\11\0\2\3\1\0\25\3\1\115\3\3\11\0\2\3"+
    "\1\0\16\3\1\203\12\3\11\0\2\3\1\0\22\3"+
    "\1\204\6\3\11\0\2\3\1\0\5\3\1\205\23\3"+
    "\11\0\2\3\1\0\10\3\1\206\20\3\11\0\2\3"+
    "\1\0\23\3\1\36\5\3\11\0\2\3\1\0\1\3"+
    "\1\207\27\3\11\0\2\3\1\0\7\3\1\210\21\3"+
    "\11\0\2\3\1\0\2\3\1\36\26\3\11\0\2\3"+
    "\1\0\14\3\1\211\14\3\11\0\2\3\1\0\14\3"+
    "\1\212\14\3\11\0\2\3\1\0\1\213\30\3\11\0"+
    "\2\3\1\0\20\3\1\214\10\3\11\0\2\3\1\0"+
    "\17\3\1\215\11\3\11\0\2\3\1\0\1\216\30\3"+
    "\11\0\2\3\1\0\17\3\1\36\11\3\11\0\2\3"+
    "\1\0\12\3\1\217\16\3\11\0\2\3\1\0\12\3"+
    "\1\50\16\3\11\0\2\3\1\0\10\3\1\220\20\3"+
    "\11\0\2\3\1\0\2\3\1\73\26\3\11\0\2\3"+
    "\1\0\11\3\1\221\17\3\11\0\2\3\1\0\1\3"+
    "\1\222\27\3\11\0\2\3\1\0\27\3\1\223\1\3"+
    "\11\0\2\3\1\0\1\224\30\3\11\0\2\3\1\0"+
    "\7\3\1\163\21\3\11\0\2\3\1\0\12\3\1\212"+
    "\16\3\11\0\2\3\1\0\3\3\1\107\25\3\11\0"+
    "\2\3\1\0\7\3\1\225\21\3\11\0\2\3\1\0"+
    "\12\3\1\226\16\3\11\0\2\3\1\0\1\3\1\36"+
    "\27\3\11\0\2\3\1\0\20\3\1\36\10\3\11\0"+
    "\2\3\1\0\2\3\1\227\26\3\11\0\2\3\1\0"+
    "\14\3\1\230\14\3\11\0\2\3\1\0\1\3\1\231"+
    "\27\3\11\0\2\3\1\0\15\3\1\115\13\3\11\0"+
    "\2\3\1\0\20\3\1\232\10\3\11\0\2\3\1\0"+
    "\12\3\1\233\16\3\11\0\2\3\1\0\20\3\1\234"+
    "\10\3\11\0\2\3\1\0\10\3\1\235\20\3\11\0"+
    "\2\3\1\0\10\3\1\236\20\3\11\0\2\3\1\0"+
    "\21\3\1\36\7\3\11\0\2\3\1\0\20\3\1\163"+
    "\10\3\11\0\2\3\1\0\11\3\1\237\17\3\11\0"+
    "\2\3\1\0\4\3\1\240\24\3\11\0\2\3\1\0"+
    "\5\3\1\115\23\3\11\0\2\3\1\0\2\3\1\241"+
    "\26\3\11\0\2\3\1\0\20\3\1\115\10\3\11\0"+
    "\2\3\1\0\10\3\1\242\20\3\11\0\2\3\1\0"+
    "\1\3\1\243\27\3\11\0\2\3\1\0\1\3\1\163"+
    "\27\3\11\0\2\3\1\0\24\3\1\36\4\3\11\0"+
    "\2\3\1\0\1\3\1\244\27\3\11\0\2\3\1\0"+
    "\10\3\1\145\20\3\11\0\2\3\1\0\4\3\1\245"+
    "\24\3\11\0\2\3\1\0\2\3\1\107\26\3\11\0"+
    "\2\3\1\0\1\246\30\3\11\0\2\3\1\0\11\3"+
    "\1\36\17\3\11\0\2\3\1\0\30\3\1\241\10\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5846];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\24\1\5\11\45\1\1\0\45\1\1\0"+
    "\27\1\1\11\47\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[166];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 106) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { return ERRO;
          }
        case 12: break;
        case 9: 
          { lexeme=yytext(); return Subtracao;
          }
        case 13: break;
        case 8: 
          { lexeme=yytext(); return Soma;
          }
        case 14: break;
        case 5: 
          { lexeme=yytext(); return Divisao;
          }
        case 15: break;
        case 11: 
          { lexeme=yytext(); return Reservadas;
          }
        case 16: break;
        case 6: 
          { lexeme=yytext(); return Linha;
          }
        case 17: break;
        case 7: 
          { lexeme=yytext(); return Igual;
          }
        case 18: break;
        case 10: 
          { lexeme=yytext(); return Multiplicacao;
          }
        case 19: break;
        case 3: 
          { lexeme=yytext(); return Numero;
          }
        case 20: break;
        case 4: 
          { /*Ignore*/
          }
        case 21: break;
        case 2: 
          { lexeme=yytext(); return Identificador;
          }
        case 22: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
