/* The following code was generated by JFlex 1.4.3 on 8/1/21 7:46 PM */

package codigo;
import static codigo.Tokens.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 8/1/21 7:46 PM from the specification file
 * <tt>E:/GitHub Projects/analisador_lexico/AnalizadorLexico/src/codigo/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\36\2\0\1\3\22\0\1\3\1\51\3\0\1\43"+
    "\1\47\1\0\1\44\1\45\1\42\1\40\1\3\1\41\1\46\1\35"+
    "\12\2\1\0\1\46\1\52\1\37\1\52\2\0\22\1\1\17\7\1"+
    "\1\46\1\0\1\46\1\0\1\1\1\0\1\16\1\12\1\24\1\7"+
    "\1\14\1\15\1\21\1\23\1\4\1\1\1\27\1\13\1\33\1\5"+
    "\1\10\1\30\1\1\1\20\1\22\1\6\1\11\1\31\1\26\1\32"+
    "\1\25\1\34\1\46\1\50\1\46\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\20\2\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\2\14\2\1\1\15"+
    "\1\16\1\2\1\17\5\2\1\17\34\2\1\4\1\20"+
    "\1\16\1\21\1\22\1\0\1\15\1\17\44\2\1\0"+
    "\27\2\1\3\4\2\1\17\3\2\1\17\36\2";

  private static int [] zzUnpackAction() {
    int [] result = new int[178];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\53\0\126\0\201\0\254\0\327\0\u0102\0\u012d"+
    "\0\u0158\0\u0183\0\u01ae\0\u01d9\0\u0204\0\u022f\0\u025a\0\u0285"+
    "\0\u02b0\0\u02db\0\u0306\0\u0331\0\u035c\0\u0387\0\53\0\u03b2"+
    "\0\u03dd\0\u0408\0\u0433\0\u0433\0\u045e\0\53\0\u0489\0\u04b4"+
    "\0\u03b2\0\u03b2\0\u04df\0\126\0\u050a\0\u0535\0\u0560\0\u058b"+
    "\0\u05b6\0\u05e1\0\u060c\0\u0637\0\u0662\0\u068d\0\u06b8\0\u06e3"+
    "\0\u070e\0\u0739\0\u0764\0\u078f\0\u07ba\0\u07e5\0\u0810\0\u083b"+
    "\0\u0866\0\u0891\0\u08bc\0\u08e7\0\u0912\0\u093d\0\u0968\0\u0993"+
    "\0\u09be\0\u09e9\0\u0a14\0\u0a3f\0\u0a6a\0\u0a95\0\u0ac0\0\53"+
    "\0\53\0\53\0\53\0\u0aeb\0\53\0\u0b16\0\u0b41\0\u0b6c"+
    "\0\u0b97\0\u0bc2\0\u0bed\0\u0c18\0\u0c43\0\u0c6e\0\u0c99\0\u0cc4"+
    "\0\u0cef\0\u0d1a\0\u0d45\0\u0d70\0\u0d9b\0\u0dc6\0\u0df1\0\u0e1c"+
    "\0\u0e47\0\u0e72\0\u0e9d\0\u0ec8\0\u0ef3\0\u0f1e\0\u0f49\0\u0f74"+
    "\0\u0f9f\0\u0fca\0\u0ff5\0\u1020\0\u104b\0\u1076\0\u10a1\0\u10cc"+
    "\0\u10f7\0\u1122\0\u114d\0\u1178\0\u11a3\0\u11ce\0\u11f9\0\u1224"+
    "\0\u124f\0\u127a\0\u12a5\0\u12d0\0\u12fb\0\u1326\0\u1351\0\u137c"+
    "\0\u13a7\0\u13d2\0\u13fd\0\u1428\0\u1453\0\u147e\0\u14a9\0\u14d4"+
    "\0\u14ff\0\u152a\0\53\0\u1555\0\u1580\0\u15ab\0\u15d6\0\u0bed"+
    "\0\u1601\0\u162c\0\u1657\0\u1682\0\u16ad\0\u16d8\0\u1703\0\u172e"+
    "\0\u1759\0\u1784\0\u17af\0\u17da\0\u1805\0\u1830\0\u185b\0\u1886"+
    "\0\u18b1\0\u18dc\0\u1907\0\u1932\0\u195d\0\u1988\0\u19b3\0\u19de"+
    "\0\u1a09\0\u1a34\0\u1a5f\0\u1a8a\0\u1ab5\0\u1ae0\0\u1b0b\0\u1b36"+
    "\0\u1b61\0\u1b8c";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[178];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\2\3\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\3\1\21\1\3\1\22\1\3\1\23\1\3\1\24"+
    "\1\25\3\3\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\2\36\1\37\1\40\1\41\1\42\54\0"+
    "\2\3\1\0\31\3\20\0\1\4\53\0\1\5\50\0"+
    "\2\3\1\0\1\3\1\43\7\3\1\44\15\3\1\45"+
    "\1\3\17\0\2\3\1\0\10\3\1\46\1\3\1\47"+
    "\16\3\17\0\2\3\1\0\14\3\1\50\2\3\1\51"+
    "\11\3\17\0\2\3\1\0\4\3\1\52\3\3\1\53"+
    "\20\3\17\0\2\3\1\0\4\3\1\54\7\3\1\55"+
    "\4\3\1\56\7\3\17\0\2\3\1\0\4\3\1\57"+
    "\24\3\17\0\2\3\1\0\7\3\1\60\16\3\1\61"+
    "\2\3\17\0\2\3\1\0\1\62\6\3\1\63\21\3"+
    "\17\0\2\3\1\0\6\3\1\64\5\3\1\65\1\3"+
    "\1\66\12\3\17\0\2\3\1\0\2\3\1\67\26\3"+
    "\17\0\2\3\1\0\10\3\1\70\20\3\17\0\2\3"+
    "\1\0\2\3\1\71\2\3\1\72\11\3\1\73\1\3"+
    "\1\74\1\75\6\3\17\0\2\3\1\0\4\3\1\76"+
    "\2\3\1\77\2\3\1\100\4\3\1\101\11\3\17\0"+
    "\2\3\1\0\17\3\1\102\11\3\17\0\2\3\1\0"+
    "\5\3\1\103\4\3\1\104\1\3\1\105\14\3\17\0"+
    "\2\3\1\0\4\3\1\106\24\3\53\0\1\107\1\0"+
    "\1\110\52\0\1\111\52\0\1\110\1\112\51\0\1\110"+
    "\1\0\1\113\50\0\1\110\54\0\1\114\50\0\1\110"+
    "\7\0\1\115\53\0\1\115\3\0\2\3\1\0\2\3"+
    "\1\116\13\3\1\117\12\3\17\0\2\3\1\0\24\3"+
    "\1\120\4\3\17\0\2\3\1\0\22\3\1\44\6\3"+
    "\17\0\2\3\1\0\2\3\1\121\26\3\17\0\2\3"+
    "\1\0\12\3\1\122\6\3\1\44\7\3\17\0\2\3"+
    "\1\0\1\123\13\3\1\124\14\3\17\0\2\3\1\0"+
    "\5\3\1\125\23\3\17\0\2\3\1\0\11\3\1\126"+
    "\17\3\17\0\2\3\1\0\4\3\1\127\24\3\17\0"+
    "\2\3\1\0\10\3\1\130\20\3\17\0\2\3\1\0"+
    "\2\3\1\131\26\3\17\0\2\3\1\0\1\3\1\132"+
    "\27\3\17\0\2\3\1\0\16\3\1\131\12\3\17\0"+
    "\2\3\1\0\2\3\1\133\26\3\17\0\2\3\1\0"+
    "\1\3\1\134\27\3\17\0\2\3\1\0\4\3\1\135"+
    "\24\3\17\0\2\3\1\0\16\3\1\136\12\3\17\0"+
    "\2\3\1\0\15\3\1\123\13\3\17\0\2\3\1\0"+
    "\16\3\1\137\12\3\17\0\2\3\1\0\14\3\1\140"+
    "\14\3\17\0\2\3\1\0\2\3\1\141\26\3\17\0"+
    "\2\3\1\0\12\3\1\142\1\3\1\143\14\3\17\0"+
    "\2\3\1\0\24\3\1\144\4\3\17\0\2\3\1\0"+
    "\4\3\1\145\24\3\17\0\2\3\1\0\1\3\1\146"+
    "\27\3\17\0\2\3\1\0\1\147\30\3\17\0\2\3"+
    "\1\0\1\3\1\150\27\3\17\0\2\3\1\0\12\3"+
    "\1\151\16\3\17\0\2\3\1\0\2\3\1\152\13\3"+
    "\1\131\12\3\17\0\2\3\1\0\12\3\1\153\16\3"+
    "\17\0\2\3\1\0\1\154\30\3\17\0\2\3\1\0"+
    "\6\3\1\155\22\3\17\0\2\3\1\0\20\3\1\156"+
    "\10\3\17\0\2\3\1\0\1\157\3\3\1\160\24\3"+
    "\17\0\2\3\1\0\1\161\6\3\1\162\21\3\16\0"+
    "\36\107\1\0\14\107\2\0\1\163\51\0\2\3\1\0"+
    "\10\3\1\164\20\3\17\0\2\3\1\0\2\3\1\165"+
    "\26\3\17\0\2\3\1\0\4\3\1\145\2\3\1\166"+
    "\21\3\17\0\2\3\1\0\1\167\30\3\17\0\2\3"+
    "\1\0\1\3\1\170\27\3\17\0\2\3\1\0\16\3"+
    "\1\44\12\3\17\0\2\3\1\0\4\3\1\171\24\3"+
    "\17\0\2\3\1\0\6\3\1\154\22\3\17\0\2\3"+
    "\1\0\12\3\1\172\16\3\17\0\2\3\1\0\7\3"+
    "\1\173\21\3\17\0\2\3\1\0\12\3\1\174\16\3"+
    "\17\0\2\3\1\0\10\3\1\44\20\3\17\0\2\3"+
    "\1\0\15\3\1\44\13\3\17\0\2\3\1\0\10\3"+
    "\1\175\20\3\17\0\2\3\1\0\12\3\1\176\16\3"+
    "\17\0\2\3\1\0\12\3\1\177\16\3\17\0\2\3"+
    "\1\0\2\3\1\200\26\3\17\0\2\3\1\0\10\3"+
    "\1\145\20\3\17\0\2\3\1\0\1\57\30\3\17\0"+
    "\2\3\1\0\5\3\1\201\23\3\17\0\2\3\1\0"+
    "\2\3\1\202\26\3\17\0\2\3\1\0\1\203\30\3"+
    "\17\0\2\3\1\0\10\3\1\153\20\3\17\0\2\3"+
    "\1\0\14\3\1\177\14\3\17\0\2\3\1\0\20\3"+
    "\1\204\10\3\17\0\2\3\1\0\2\3\1\152\26\3"+
    "\17\0\2\3\1\0\2\3\1\205\26\3\17\0\2\3"+
    "\1\0\16\3\1\123\12\3\17\0\2\3\1\0\20\3"+
    "\1\206\10\3\17\0\2\3\1\0\14\3\1\44\14\3"+
    "\17\0\2\3\1\0\7\3\1\131\21\3\17\0\2\3"+
    "\1\0\7\3\1\202\21\3\17\0\2\3\1\0\23\3"+
    "\1\207\5\3\17\0\2\3\1\0\25\3\1\210\3\3"+
    "\17\0\2\3\1\0\2\3\1\211\26\3\17\0\2\3"+
    "\1\0\3\3\1\44\25\3\17\0\2\3\1\0\12\3"+
    "\1\212\16\3\20\0\1\163\42\0\1\213\6\0\2\3"+
    "\1\0\14\3\1\214\14\3\17\0\2\3\1\0\12\3"+
    "\1\215\16\3\17\0\2\3\1\0\10\3\1\216\20\3"+
    "\17\0\2\3\1\0\25\3\1\131\3\3\17\0\2\3"+
    "\1\0\16\3\1\217\12\3\17\0\2\3\1\0\22\3"+
    "\1\220\6\3\17\0\2\3\1\0\5\3\1\221\23\3"+
    "\17\0\2\3\1\0\10\3\1\222\20\3\17\0\2\3"+
    "\1\0\23\3\1\44\5\3\17\0\2\3\1\0\1\3"+
    "\1\223\27\3\17\0\2\3\1\0\7\3\1\224\21\3"+
    "\17\0\2\3\1\0\2\3\1\44\26\3\17\0\2\3"+
    "\1\0\14\3\1\225\14\3\17\0\2\3\1\0\14\3"+
    "\1\226\14\3\17\0\2\3\1\0\1\227\30\3\17\0"+
    "\2\3\1\0\20\3\1\230\10\3\17\0\2\3\1\0"+
    "\17\3\1\231\11\3\17\0\2\3\1\0\1\232\30\3"+
    "\17\0\2\3\1\0\17\3\1\44\11\3\17\0\2\3"+
    "\1\0\12\3\1\233\16\3\17\0\2\3\1\0\12\3"+
    "\1\56\16\3\17\0\2\3\1\0\10\3\1\234\20\3"+
    "\17\0\2\3\1\0\2\3\1\102\26\3\17\0\2\3"+
    "\1\0\11\3\1\235\17\3\17\0\2\3\1\0\1\3"+
    "\1\236\27\3\17\0\2\3\1\0\27\3\1\237\1\3"+
    "\17\0\2\3\1\0\1\240\30\3\17\0\2\3\1\0"+
    "\7\3\1\177\21\3\17\0\2\3\1\0\12\3\1\226"+
    "\16\3\17\0\2\3\1\0\3\3\1\123\25\3\17\0"+
    "\2\3\1\0\7\3\1\241\21\3\17\0\2\3\1\0"+
    "\12\3\1\242\16\3\17\0\2\3\1\0\1\3\1\44"+
    "\27\3\17\0\2\3\1\0\20\3\1\44\10\3\17\0"+
    "\2\3\1\0\2\3\1\243\26\3\17\0\2\3\1\0"+
    "\14\3\1\244\14\3\17\0\2\3\1\0\1\3\1\245"+
    "\27\3\17\0\2\3\1\0\15\3\1\131\13\3\17\0"+
    "\2\3\1\0\20\3\1\246\10\3\17\0\2\3\1\0"+
    "\12\3\1\247\16\3\17\0\2\3\1\0\20\3\1\250"+
    "\10\3\17\0\2\3\1\0\10\3\1\251\20\3\17\0"+
    "\2\3\1\0\10\3\1\252\20\3\17\0\2\3\1\0"+
    "\21\3\1\44\7\3\17\0\2\3\1\0\20\3\1\177"+
    "\10\3\17\0\2\3\1\0\11\3\1\253\17\3\17\0"+
    "\2\3\1\0\4\3\1\254\24\3\17\0\2\3\1\0"+
    "\5\3\1\131\23\3\17\0\2\3\1\0\2\3\1\255"+
    "\26\3\17\0\2\3\1\0\20\3\1\131\10\3\17\0"+
    "\2\3\1\0\10\3\1\256\20\3\17\0\2\3\1\0"+
    "\1\3\1\257\27\3\17\0\2\3\1\0\1\3\1\177"+
    "\27\3\17\0\2\3\1\0\24\3\1\44\4\3\17\0"+
    "\2\3\1\0\1\3\1\260\27\3\17\0\2\3\1\0"+
    "\10\3\1\161\20\3\17\0\2\3\1\0\4\3\1\261"+
    "\24\3\17\0\2\3\1\0\2\3\1\123\26\3\17\0"+
    "\2\3\1\0\1\262\30\3\17\0\2\3\1\0\11\3"+
    "\1\44\17\3\17\0\2\3\1\0\30\3\1\255\16\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7095];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\24\1\1\11\6\1\1\11\51\1\4\11"+
    "\1\0\1\11\45\1\1\0\27\1\1\11\47\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[178];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexeme;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 132) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 17: 
          { lexeme=yytext(); return Incremento;
          }
        case 19: break;
        case 6: 
          { lexeme=yytext(); return Linha;
          }
        case 20: break;
        case 8: 
          { lexeme=yytext(); return Soma;
          }
        case 21: break;
        case 13: 
          { lexeme=yytext(); return Op_Logico;
          }
        case 22: break;
        case 1: 
          { return ERRO;
          }
        case 23: break;
        case 15: 
          { lexeme=yytext(); return Reservada;
          }
        case 24: break;
        case 12: 
          { lexeme=yytext(); return Separador;
          }
        case 25: break;
        case 10: 
          { lexeme=yytext(); return Multiplicacao;
          }
        case 26: break;
        case 18: 
          { lexeme=yytext(); return Decremento;
          }
        case 27: break;
        case 9: 
          { lexeme=yytext(); return Subtracao;
          }
        case 28: break;
        case 5: 
          { lexeme=yytext(); return Divisao;
          }
        case 29: break;
        case 7: 
          { lexeme=yytext(); return Igual;
          }
        case 30: break;
        case 3: 
          { lexeme=yytext(); return Numero;
          }
        case 31: break;
        case 2: 
          { lexeme=yytext(); return Identificador;
          }
        case 32: break;
        case 11: 
          { lexeme=yytext(); return Resto;
          }
        case 33: break;
        case 16: 
          { lexeme=yytext(); return Op_Atribuicao;
          }
        case 34: break;
        case 4: 
          { /*Ignore*/
          }
        case 35: break;
        case 14: 
          { lexeme=yytext(); return Op_Comparacao;
          }
        case 36: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
